<a href="https://colab.research.google.com/github/thecoducer/learning-data-science/blob/master/Learning_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy###

### Why Numpy is faster than lists?

- Numpy is faster than lists since Numpy elements have fixed data type.
- Numpy has contiguous memory
- No type checking when reading objects
- Read bytes of memory faster

### Applications of Numpy:

- Mathematics (MATLAB replacement)
- Plotting (using matloptlib)
- Backend (Pandas, Connect 4, Digital photography)
- Machine learning (Numpy helps to give a foundation to tensors)

## Install numpy

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## To turn autocomplete suggestions in notebook

In [97]:
%config IPCompleter.greedy=True

## Importing Numpy

In [6]:
import numpy as np

## 1 dimensional matrix

In [7]:
a = np.array([45, 58, 96], dtype="int16")
print(a)

[45 58 96]


## 2 dimensional matrix

In [8]:
b = np.array([[4, 5, 8], [2, 7, 6]])
print(b)

[[4 5 8]
 [2 7 6]]


## 3 dimensional matrix

In [9]:
c = np.array([[1.23, 2.23, 3.89], [9, 6, 9], [7, 2, 4]])
print(c)

[[1.23 2.23 3.89]
 [9.   6.   9.  ]
 [7.   2.   4.  ]]


In [10]:
# Get dimension
a.ndim

1

In [11]:
# Get shape or n * n?
b.shape

(2, 3)

In [12]:
# Get type
print(a.dtype)
print(c.dtype)

int16
float64


In [13]:
# Get bytes of memory it takes
print(b.itemsize)
print(a.itemsize)
print(c.itemsize)
# 2 bytes for int16
# 4 bytes for int32
# 8 bytes for int64
# 8 bytes for float too

8
2
8


In [14]:
# Get length of np array
print(a.size)
print(b.size)
print(c.size)

3
6
9


In [15]:
# Get total size
print(a.size * a.itemsize)
# other way to do this
print(a.nbytes)

6
6


## Acccessing/Changing specific elements, rows, columns etc.

In [16]:
d = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element - [r, c]
d[0, 3]

4

In [18]:
# Get a specific row
print(d[0, :]) # first row
print(d[0, 1:6])

[1 2 3 4 5 6 7]
[2 3 4 5 6]


In [19]:
# Get a specific column
print(d[:, 2]) # third column

[ 3 10]


In [20]:
# Getting little more fancy [startindex:endindex:stepsize]
print(d[0, 1:-1:2])

[2 4 6]


In [21]:
# Replace elements
d[1, 4] = 55
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 55 13 14]]


In [22]:
d[:, 2] = [117, 17]
print(d)

[[  1   2 117   4   5   6   7]
 [  8   9  17  11  55  13  14]]


In [23]:
# Just another matrix
f = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
print(f[0, 1, 0]) # accessing a elements is easy if we do it pathwise

3


In [25]:
print(f[:, ])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Replace elements
f[0, 1] = [52, 65]
print(f)

[[[ 1  2]
  [52 65]]

 [[ 5  6]
  [ 7  8]]]


In [33]:
f[:, 1, :] = [[4, 8], [9, 2]]
print(f)

[[[1 2]
  [4 8]]

 [[5 6]
  [9 2]]]


# Initializing different types of arrays

In [36]:
# All 0s matrix
# In bracket we give the shape
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [41]:
# All 1s matrix
pp = np.ones((5, 5), dtype='int16')
print(pp)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [45]:
# Any other number
oo = np.full((8, 3), 5, dtype="float32")
print(oo)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [56]:
# Any other number (full_like)
fl = np.full_like(f, 5)
print(fl)

[[[5 5]
  [5 5]]

 [[5 5]
  [5 5]]]


In [62]:
#Random number matrix
np.random.rand(2, 5)

array([[0.03825537, 0.49263154, 0.38272094, 0.48620256, 0.6374759 ],
       [0.64430633, 0.2188755 , 0.07258313, 0.71476633, 0.09294047]])

In [60]:
#Random number matrix using shape of an already created matrix
np.random.random_sample(fl.shape)

array([[[0.16112133, 0.31930141],
        [0.22613974, 0.07782528]],

       [[0.94565545, 0.57325914],
        [0.26166416, 0.93243123]]])

In [95]:
#Random integer values
np.random.randint(5, 9, size=(2, 3, 4))

array([[[7, 6, 7, 7],
        [5, 6, 6, 7],
        [5, 7, 8, 8]],

       [[7, 6, 5, 8],
        [6, 7, 5, 5],
        [6, 7, 5, 6]]])

In [103]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
i = np.identity(4, dtype="int32");
print(i)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [111]:
#Repeat
arr = np.array([[78, 54]])
rp = np.repeat(arr, 4, axis=0)
print(rp)

[[78 54]
 [78 54]
 [78 54]
 [78 54]]
