<a href="https://colab.research.google.com/github/thecoducer/learning-data-science/blob/master/Learning_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy###

### Why Numpy is faster than lists?

- Numpy is faster than lists since Numpy elements have fixed data type.
- Numpy has contiguous memory
- No type checking when reading objects
- Read bytes of memory faster

### Applications of Numpy:

- Mathematics (MATLAB replacement)
- Plotting (using matloptlib)
- Backend (Pandas, Connect 4, Digital photography)
- Machine learning (Numpy helps to give a foundation to tensors)

## Install numpy

In [1]:
pip install numpy

In [0]:
import numpy as np

In [8]:
a = np.array([45, 58, 96])
print(a)

[45 58 96]


In [9]:
b = np.array([[4, 5, 8], [2, 7, 6]])
print(b)

[[4 5 8]
 [2 7 6]]
