<a href="https://colab.research.google.com/github/thecoducer/learning-data-science/blob/master/Learning_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy###

### Why Numpy is faster than lists?

- Numpy is faster than lists since Numpy elements have fixed data type.
- Numpy has contiguous memory
- No type checking when reading objects
- Read bytes of memory faster

### Applications of Numpy:

- Mathematics (MATLAB replacement)
- Plotting (using matloptlib)
- Backend (Pandas, Connect 4, Digital photography)
- Machine learning (Numpy helps to give a foundation to tensors)

## Install numpy

In [45]:
pip install numpy

## Importing Numpy

In [0]:
import numpy as np

## 1 dimensional matrix

In [47]:
a = np.array([45, 58, 96], dtype="int16")
print(a)

[45 58 96]


## 2 dimensional matrix

In [48]:
b = np.array([[4, 5, 8], [2, 7, 6]])
print(b)

[[4 5 8]
 [2 7 6]]


## 3 dimensional matrix

In [49]:
c = np.array([[1.23, 2.23, 3.89], [9, 6, 9], [7, 2, 4]])
print(c)

[[1.23 2.23 3.89]
 [9.   6.   9.  ]
 [7.   2.   4.  ]]


In [50]:
# Get dimension
a.ndim

1

In [51]:
# Get shape or n * n?
b.shape

(2, 3)

In [52]:
# Get type
print(a.dtype)
print(c.dtype)

int16
float64


In [56]:
# Get bytes of memory it takes
print(b.itemsize)
print(a.itemsize)
print(c.itemsize)
# 2 bytes for int16
# 4 bytes for int32
# 8 bytes for int64
# 8 bytes for float too

8
2
8


In [54]:
# Get length of np array
print(a.size)
print(b.size)
print(c.size)

3
6
9


In [55]:
# Get total size
print(a.size * a.itemsize)
# other way to do this
print(a.nbytes)

6
6


## Acccessing/Changing specific elements, rows, columns etc.

In [57]:
d = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [59]:
# Get a specific element - [r, c]
d[0, 3]

4

In [64]:
# Get a specific row
print(d[0, :]) # first row
print(d[0, 1:6])

[1 2 3 4 5 6 7]
[2 3 4 5 6]


In [65]:
# Get a specific column
print(d[:, 2]) # third column

[ 3 10]
